### ISSUE TITLE
Cordova Plugin Inappbrowser Giving Errors on run

### ISSUE THREAD

**Issue by thesourav123** [Tommertom/diyDevApp#2]
App is built , cordova plugin has been added. But, when the inappbrowser is called, it is giving the following error
ReferenceError: cordova is not defined
    at openBrowser (http://10.90.84.82:8100/js/services.js:101:7)
    at http://10.90.84.82:8100/js/services.js:322:22
    at http://10.90.84.82:8100/lib/ionic/js/ionic.bundle.min.js:162:305
    at m.$eval (http://10.90.84.82:8100/lib/ionic/js/ionic.bundle.min.js:176:467)
    at m.$digest (http://10.90.84.82:8100/lib/ionic/js/ionic.bundle.min.js:174:47)
    at b.$apply (http://10.90.84.82:8100/lib/ionic/js/ionic.bundle.min.js:177:249)
    at HTMLButtonElement.<anonymous> (http://10.90.84.82:8100/lib/ionic/js/ionic.bundle.min.js:472:11589)
    at HTMLButtonElement.dispatch (https://code.jquery.com/jquery-3.1.1.min.js:3:10315)
    at HTMLButtonElement.q.handle (https://code.jquery.com/jquery-3.1.1.min.js:3:8342)
    at n (http://10.90.84.82:8100/lib/ionic/js/ionic.bundle.min.js:22:384)

**Comment by Tommertom** [comment]
Good one!

I think the injection plugin does inject cordova.js in the new window

I can look at it next week probably but likely needs some investigation with the plugin itself

**Comment by thesourav123** [comment]
kool thanks..kindly keep me posted. Great Work by the way, Its way more flexible and easy to work with

**Comment by thesourav123** [comment]
i think the issue is with deviceready not being fired before the browser is called.

**Comment by Tommertom** [comment]
Ok. So consider closed? Otherwise plse post the code u use

**Comment by thesourav123** [comment]
No, please dont close it. I don't have the solution, i just found a probable cause. In my current app, the inappbrowser is called for oAuth authorization in the start, which might not be working for DevApp context. So now i will try to create another client app where i call inappbrowser inside a button or something and will see what happens.

Thanks

**Comment by thesourav123** [comment]
Nope, inappbrowser not opening at all. Created a simple project with a button to open the browser
https://github.com/thesourav123/devapp_testing .

**Comment by Tommertom** [comment]
Can't reproduce with your repo - the button click does not trigger event (and small syntax issue on line 31 of app.js). Iam not into angular v1.

Mine seems to work:  https://github.com/Tommertom/inappbrowsertest

After adding inAppBrowser to diyDevApp: `ionic cordova plugin add cordova-plugin-inappbrowser`
